### ISSUE TITLE
Добавить необработанные изображения для фона в репозиторию

### ISSUE THREAD

**Issue by ub** [fallacymania/fallacymania.com#14]
Чтобы не потерялись, когда будем полировать стили -- пусть наряду с используемыми для сайта обработанными изображениями будут лежать их оригиналы jpeg или png.
Пока будем класть вместе со всеми в app/assets/images -- когда станет слишком много, переместим 
в отдельную папочку

- app/assets/images/bg-about.jpg
- app/assets/images/bg-downloads.jpg
- app/assets/images/bg-game.jpg
- app/assets/images/bg-home.jpg

Положи, например, с префиксом src- :  app/assets/images/src-bg-about.jpg и т.п.

**Comment by Alexander230** [comment]
Добавил их с суффиксом -original: https://github.com/fallacymania/fallacymania.com/commit/e659d2ba3c9ffb3e3f8047534636f8d28113c74b

**Comment by ub** [comment]
спасибо!
