### ISSUE TITLE
Съехавшее верхнее меню при переходе в блог с главной страницы сайта

### ISSUE THREAD

**Issue by Alexander230** [fallacymania/fallacymania.com#15]
При переходе с главной страницы fallacymania.com в блог через кнопку "Блог" в правом верхнем углу, верхнее меню в блоге оказывается съехавшим. После обновления страницы приходит в норму. Воспроизводится в браузерах Chrome 61 и Firefox 56.

**Comment by ub** [comment]
Из-за  turbolinks браузер сохранял  таблицу стилей основного сайта при рендеринге блога.
Потребовалось явно отключить turbolinks  для ссылки, которая выглядела для Rails как локальная
